In [1]:
print("hello world")

hello world


In [2]:
from numpy import *

In [3]:
a=array([2,4,5,7])
print(a)

[2 4 5 7]


In [4]:
a[0]

2

In [5]:
for i in a :
print(i)

2
4
5
7


In [6]:
a=array([
    [1,2,4,6],
    [4,8,9,0]

])
a

array([[1, 2, 4, 6],
       [4, 8, 9, 0]])

In [7]:
a.ndim

2

In [8]:
a.shape

(2, 4)

In [9]:
a.dtype

dtype('int64')

In [10]:
b=zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [11]:
print("since they are in float values but what if we want integers values")
b=array([[1,2],[1,5]],dtype=float)
b

since they are in float values but what if we want integers values


array([[1., 2.],
       [1., 5.]])

In [12]:
b=zeros((3,3),dtype=int)
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
z=ones((5,5))
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
'''if we want the numbers in the row we can use the name as arange'''
arange(5)

array([0, 1, 2, 3, 4])

In [15]:
c=array(['hello'])
d=array(['hii'])
print(char.add(c,d))

['hellohii']


In [16]:
a=([1,3,4])
b=([5,7,8])
e=3
z=a+b
print(z)

[1, 3, 4, 5, 7, 8]


# matrix mathematics

In [17]:
a=arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
b=arange(10,19,1).reshape(3,3)

In [19]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [20]:
m1=matrix(a)
m2=matrix(b)

In [21]:
print(m1+m2)
print()
print(m1-m2)
print()
print(m1/m2)
print()
print(m1*m2)
print()

[[10 12 14]
 [16 18 20]
 [22 24 26]]

[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]

[[0.         0.09090909 0.16666667]
 [0.23076923 0.28571429 0.33333333]
 [0.375      0.41176471 0.44444444]]

[[ 45  48  51]
 [162 174 186]
 [279 300 321]]



In [22]:
print(add(a,b))

[[10 12 14]
 [16 18 20]
 [22 24 26]]


In [23]:
print(char.multiply(c,e))

['hellohellohello']


In [24]:
print(char.capitalize("hello"))

Hello


In [25]:
print(char.lower(['NIKHIL','naveen']))

['nikhil' 'naveen']


In [26]:
print(char.upper(['nikhil is a good boy']))

['NIKHIL IS A GOOD BOY']


In [27]:
print(char.split('now he is a coder'))

['now', 'he', 'is', 'a', 'coder']


# array manipulation

In [28]:
a=arange(10)
print("the original array is")
print(a)

the original array is
[0 1 2 3 4 5 6 7 8 9]


In [29]:
b=a.reshape(5,2)

In [30]:
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [31]:
print(b.flatten())

[0 1 2 3 4 5 6 7 8 9]


In [32]:
a=arange(9).reshape(3,3)

In [33]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
transpose(a)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

# numpy arithmetic operations

In [35]:
a=arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
b=array([10,11,12])

In [37]:
print(add(a,b))

[[10 12 14]
 [13 15 17]
 [16 18 20]]


In [38]:
c=array(b)

In [39]:
print(subtract(a,c))

[[-10 -10 -10]
 [ -7  -7  -7]
 [ -4  -4  -4]]


In [40]:
print(multiply(a,b))

[[ 0 11 24]
 [30 44 60]
 [60 77 96]]


In [41]:
d=arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
print(multiply(a,d))

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


#Slicing

#slicing

In [44]:
a=arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
a[:4]

array([0, 1, 2, 3])

In [46]:
a[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
print("for using slice option we have to use the start,end,step size")
s=slice(2,10,2)
print(a[s])
print(a[slice(2,12,3)])

for using slice option we have to use the start,end,step size
[2 4 6 8]
[ 2  5  8 11]


# iterating data over array

In [48]:
a=arange(0,90,10).reshape(3,3)

In [49]:
a

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [50]:
for i in nditer(a):
    print(i)

0
10
20
30
40
50
60
70
80


# iterating through the row and column

In [51]:
print(a)

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]


In [52]:
print(a)
print()
print("element in the column wise")
for i in nditer(a,order='F'):
    print(i)
print()
print("elements in the row wise it is used as inbuilt")
for i in nditer(a,order='c'): 
    print(i)

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]

element in the column wise
0
30
60
10
40
70
20
50
80

elements in the row wise it is used as inbuilt
0
10
20
30
40
50
60
70
80


# splitting of arrays

In [53]:
a=arange(9)
b=a.reshape(3,3)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
print(split(a,3))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [55]:
# splitting in more than two arrays
# split(0 index to stop index,next stop index,next stop index.......)

In [56]:
split(a,[4,7])

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [57]:
split(a,[2,4,7])

[array([0, 1]), array([2, 3]), array([4, 5, 6]), array([7, 8])]

# Resizing of an array

In [58]:
a=array([[1,2,3],[5,8,9]])

In [59]:
print(a.shape)

(2, 3)


In [60]:
b=resize(a,[2,3])
print(b)
print()
print(b.shape)

[[1 2 3]
 [5 8 9]]

(2, 3)


# Histogram

In [64]:
a=arange(9).reshape(3,3)